const vk = @import("vk");
const std = @import("std");
const log = std.log.scoped(.SDL);

pub const InitFlags = packed struct(u32) {
    _padding1: u4 = 0,
    audio: bool = false,
    video: bool = false,
    _padding2: u3 = 0,
    joystick: bool = false,
    _padding3: u2 = 0,
    haptic: bool = false,
    gamepad: bool = false,
    events: bool = false,
    sensor: bool = false,
    camera: bool = false,
    _padding4: u15 = 0,
};

pub const WindowFlags = packed struct(u32) {
    fullscreen: bool = false,
    opengl: bool = false,
    occluded: bool = false,
    hidden: bool = false,
    borderless: bool = false,
    resizable: bool = false,
    minimized: bool = false,
    maximized: bool = false,
    mouse_grabbed: bool = false,
    input_focus: bool = false,
    mouse_focus: bool = false,
    external: bool = false,
    modal: bool = false,
    high_pixel_density: bool = false,
    mouse_capture: bool = false,
    mouse_relative_mode: bool = false,
    always_on_top: bool = false,
    utility: bool = false,
    tooltip: bool = false,
    popup_menu: bool = false,
    keyboard_grabbed: bool = false,
    fill_document: bool = false,
    vulkan: bool = false,
    metal: bool = false,
    transparent: bool = false,
    not_focusable: bool = false,
    reserved: u6 = 0,
};

pub const EventType = enum(u32) {
    first = 0,
    quit = 0x100,
    terminating,
    low_memory,
    will_enter_background,
    did_enter_background,
    will_enter_foreground,
    did_enter_foreground,
    locale_changed,
    system_theme_changed,
    display_orientation = 0x151,
    display_added,
    display_removed,
    display_moved,
    display_desktop_mode_changed,
    display_current_mode_changed,
    display_content_scale_changed,
    display_usable_bounds_changed,
    // display_first = display_orientation,
    // display_last = display_usable_bounds_changed,
    window_shown = 0x202,
    window_hidden,
    window_exposed,
    window_moved,
    window_resized,
    window_pixel_size_changed,
    window_metal_view_resized,
    window_minimized,
    window_maximized,
    window_restored,
    window_mouse_enter,
    window_mouse_leave,
    window_focus_gained,
    window_focus_lost,
    window_close_requested,
    window_hit_test,
    window_iccprof_changed,
    window_display_changed,
    window_display_scale_changed,
    window_safe_area_changed,
    window_occluded,
    window_enter_fullscreen,
    window_leave_fullscreen,
    window_destroyed,
    window_hdr_state_changed,
    // window_first = window_shown,
    // window_last = window_hdr_state_changed,
    key_down = 0x300,
    key_up,
    text_editing,
    text_input,
    keymap_changed,
    keyboard_added,
    keyboard_removed,
    text_editing_candidates,
    screen_keyboard_shown,
    screen_keyboard_hidden,
    mouse_motion = 0x400,
    mouse_button_down,
    mouse_button_up,
    mouse_wheel,
    mouse_added,
    mouse_removed,
    joystick_axis_motion = 0x600,
    joystick_ball_motion,
    joystick_hat_motion,
    joystick_button_down,
    joystick_button_up,
    joystick_added,
    joystick_removed,
    joystick_battery_updated,
    joystick_update_complete,
    gamepad_axis_motion = 0x650,
    gamepad_button_down,
    gamepad_button_up,
    gamepad_added,
    gamepad_removed,
    gamepad_remapped,
    gamepad_touchpad_down,
    gamepad_touchpad_motion,
    gamepad_touchpad_up,
    gamepad_sensor_update,
    gamepad_update_complete,
    gamepad_steam_handle_updated,
    finger_down = 0x700,
    finger_up,
    finger_motion,
    finger_canceled,
    pinch_begin = 0x710,
    pinch_update,
    pinch_end,
    clipboard_update = 0x900,
    drop_file = 0x1000,
    drop_text,
    drop_begin,
    drop_complete,
    drop_position,
    audio_device_added = 0x1100,
    audio_device_removed,
    audio_device_format_changed,
    sensor_update = 0x1200,
    pen_proximity_in = 0x1300,
    pen_proximity_out,
    pen_down,
    pen_up,
    pen_button_down,
    pen_button_up,
    pen_motion,
    pen_axis,
    camera_device_added = 0x1400,
    camera_device_removed,
    camera_device_approved,
    camera_device_denied,
    render_targets_reset = 0x2000,
    render_device_reset,
    render_device_lost,
    private0 = 0x4000,
    private1,
    private2,
    private3,
    poll_sentinel = 0x7f00,
    user = 0x8000,
    last = 0xffff,
    enum_padding = 0x7fffffff,
};

pub const WindowID = enum(u32) { _ };
pub const KeyboardID = enum(u32) { _ };
pub const MouseID = enum(u32) { _ };

pub const Scancode = enum(u32) {
    unknown = 0,
    a = 4,
    b = 5,
    c = 6,
    d = 7,
    e = 8,
    f = 9,
    g = 10,
    h = 11,
    i = 12,
    j = 13,
    k = 14,
    l = 15,
    m = 16,
    n = 17,
    o = 18,
    p = 19,
    q = 20,
    r = 21,
    s = 22,
    t = 23,
    u = 24,
    v = 25,
    w = 26,
    x = 27,
    y = 28,
    z = 29,
    @"1" = 30,
    @"2" = 31,
    @"3" = 32,
    @"4" = 33,
    @"5" = 34,
    @"6" = 35,
    @"7" = 36,
    @"8" = 37,
    @"9" = 38,
    @"0" = 39,
    @"return" = 40,
    escape = 41,
    backspace = 42,
    tab = 43,
    space = 44,
    minus = 45,
    equals = 46,
    leftbracket = 47,
    rightbracket = 48,
    backslash = 49,
    nonushash = 50,
    semicolon = 51,
    apostrophe = 52,
    grave = 53,
    comma = 54,
    period = 55,
    slash = 56,
    capslock = 57,
    f1 = 58,
    f2 = 59,
    f3 = 60,
    f4 = 61,
    f5 = 62,
    f6 = 63,
    f7 = 64,
    f8 = 65,
    f9 = 66,
    f10 = 67,
    f11 = 68,
    f12 = 69,
    printscreen = 70,
    scrolllock = 71,
    pause = 72,
    insert = 73,
    home = 74,
    pageup = 75,
    delete = 76,
    end = 77,
    pagedown = 78,
    right = 79,
    left = 80,
    down = 81,
    up = 82,
    numlockclear = 83,
    kp_divide = 84,
    kp_multiply = 85,
    kp_minus = 86,
    kp_plus = 87,
    kp_enter = 88,
    kp_1 = 89,
    kp_2 = 90,
    kp_3 = 91,
    kp_4 = 92,
    kp_5 = 93,
    kp_6 = 94,
    kp_7 = 95,
    kp_8 = 96,
    kp_9 = 97,
    kp_0 = 98,
    kp_period = 99,
    nonusbackslash = 100,
    application = 101,
    power = 102,
    kp_equals = 103,
    f13 = 104,
    f14 = 105,
    f15 = 106,
    f16 = 107,
    f17 = 108,
    f18 = 109,
    f19 = 110,
    f20 = 111,
    f21 = 112,
    f22 = 113,
    f23 = 114,
    f24 = 115,
    execute = 116,
    help = 117,
    menu = 118,
    select = 119,
    stop = 120,
    again = 121,
    undo = 122,
    cut = 123,
    copy = 124,
    paste = 125,
    find = 126,
    mute = 127,
    volumeup = 128,
    volumedown = 129,
    kp_comma = 133,
    kp_equalsas400 = 134,
    international1 = 135,
    international2 = 136,
    international3 = 137,
    international4 = 138,
    international5 = 139,
    international6 = 140,
    international7 = 141,
    international8 = 142,
    international9 = 143,
    lang1 = 144,
    lang2 = 145,
    lang3 = 146,
    lang4 = 147,
    lang5 = 148,
    lang6 = 149,
    lang7 = 150,
    lang8 = 151,
    lang9 = 152,
    alterase = 153,
    sysreq = 154,
    cancel = 155,
    clear = 156,
    prior = 157,
    return2 = 158,
    separator = 159,
    out = 160,
    oper = 161,
    clearagain = 162,
    crsel = 163,
    exsel = 164,
    kp_00 = 176,
    kp_000 = 177,
    thousandsseparator = 178,
    decimalseparator = 179,
    currencyunit = 180,
    currencysubunit = 181,
    kp_leftparen = 182,
    kp_rightparen = 183,
    kp_leftbrace = 184,
    kp_rightbrace = 185,
    kp_tab = 186,
    kp_backspace = 187,
    kp_a = 188,
    kp_b = 189,
    kp_c = 190,
    kp_d = 191,
    kp_e = 192,
    kp_f = 193,
    kp_xor = 194,
    kp_power = 195,
    kp_percent = 196,
    kp_less = 197,
    kp_greater = 198,
    kp_ampersand = 199,
    kp_dblampersand = 200,
    kp_verticalbar = 201,
    kp_dblverticalbar = 202,
    kp_colon = 203,
    kp_hash = 204,
    kp_space = 205,
    kp_at = 206,
    kp_exclam = 207,
    kp_memstore = 208,
    kp_memrecall = 209,
    kp_memclear = 210,
    kp_memadd = 211,
    kp_memsubtract = 212,
    kp_memmultiply = 213,
    kp_memdivide = 214,
    kp_plusminus = 215,
    kp_clear = 216,
    kp_clearentry = 217,
    kp_binary = 218,
    kp_octal = 219,
    kp_decimal = 220,
    kp_hexadecimal = 221,
    lctrl = 224,
    lshift = 225,
    lalt = 226,
    lgui = 227,
    rctrl = 228,
    rshift = 229,
    ralt = 230,
    rgui = 231,
    mode = 257,
    sleep = 258,
    wake = 259,
    channel_increment = 260,
    channel_decrement = 261,
    media_play = 262,
    media_pause = 263,
    media_record = 264,
    media_fast_forward = 265,
    media_rewind = 266,
    media_next_track = 267,
    media_previous_track = 268,
    media_stop = 269,
    media_eject = 270,
    media_play_pause = 271,
    media_select = 272,
    ac_new = 273,
    ac_open = 274,
    ac_close = 275,
    ac_exit = 276,
    ac_save = 277,
    ac_print = 278,
    ac_properties = 279,
    ac_search = 280,
    ac_home = 281,
    ac_back = 282,
    ac_forward = 283,
    ac_stop = 284,
    ac_refresh = 285,
    ac_bookmarks = 286,
    softleft = 287,
    softright = 288,
    call = 289,
    endcall = 290,
    reserved = 400,
    count = 512,
};

pub const Keymod = packed struct(u16) {
    lshift: bool = false,
    rshift: bool = false,
    level5: bool = false,
    _padding1: u3 = 0,
    lctrl: bool = false,
    rctrl: bool = false,
    lalt: bool = false,
    ralt: bool = false,
    lgui: bool = false,
    rgui: bool = false,
    num: bool = false,
    caps: bool = false,
    mode: bool = false,
    scroll: bool = false,
};

pub const KeyboardEvent = extern struct {
    type: EventType,
    reserved: u32,
    timestamp: u64,
    windowID: WindowID,
    which: KeyboardID,
    scancode: Scancode,
    key: u32, //im lazy
    mod: Keymod,
    raw: u16,
    down: bool,
    repeat: bool,
};

pub const MouseButtonFlags = packed struct(u32) {
    left: u1 = 0,
    middle: u1 = 0,
    right: u1 = 0,
    x1: u1 = 0,
    x2: u1 = 0,
    _padding: u27 = 0,
};

pub const MouseMotionEvent = extern struct {
    type: EventType,
    reserved: u32,
    timestamp: u64,
    windowID: WindowID,
    which: MouseID,
    state: MouseButtonFlags,
    x: f32,
    y: f32,
    xrel: f32,
    yrel: f32,
};

pub const Event = extern union {
    type: EventType,
    key: KeyboardEvent,
    motion: MouseMotionEvent,
    padding: [128]u8,
};

pub const Window_t = opaque {};
pub const Window = *Window_t;

//binds

//input
pub const pollEvent = @extern(*const fn (event: *Event) callconv(.c) bool, .{ .name = "SDL_PollEvent" });
pub const pumpEvents = @extern(*const fn () callconv(.c) void, .{ .name = "SDL_PumpEvents" });
pub const getKeyboardState = @extern(*const fn (keynum: ?*i32) callconv(.c) [*]bool, .{ .name = "SDL_GetKeyboardState" });

pub const getError = @extern(*const fn () callconv(.c) [*:0]const u8, .{ .name = "SDL_GetError" });

pub const raw_init = @extern(*const fn (InitFlags) callconv(.c) bool, .{ .name = "SDL_Init" });
pub fn init(flags: InitFlags) error{Init}!void {
    const result = raw_init(flags);
    if (!result) {
        log.err("{s}", .{getError()});
        return error.Init;
    }
}

pub const raw_createWindow = @extern(*const fn (title: [*:0]const u8, w: i32, h: i32, flags: WindowFlags) callconv(.c) ?Window, .{ .name = "SDL_CreateWindow" });
pub fn createWindow(title: [*:0]const u8, w: i32, h: i32, flags: WindowFlags) error{createWindow}!Window {
    return raw_createWindow(title, w, h, flags) orelse {
        log.err("{s}", .{getError()});
        return error.createWindow;
    };
}
pub const destroyWindow = @extern(*const fn (window: *Window) callconv(.c) void, .{ .name = "SDL_DestroyWindow" });

pub const quitSubsystem = @extern(*const fn (flags: InitFlags) callconv(.c) void, .{ .name = "SDL_QuitSubSystem" });

pub const getWindowSize = @extern(*const fn (window: Window, w: *i32, h: *i32) callconv(.c) bool, .{ .name = "SDL_GetWindowSize" });
pub const setWindowRelativeMouseMode = @extern(*const fn (window: Window, enable: bool) callconv(.c) bool, .{ .name = "SDL_SetWindowRelativeMouseMode" });
pub const deinit = @extern(*const fn () callconv(.c) void, .{ .name = "SDL_Quit" });

pub const vulkan = struct {
    const raw_loadLibrary = @extern(*const fn (path: ?[*:0]const u8) callconv(.c) bool, .{ .name = "SDL_Vulkan_LoadLibrary" });
    pub fn loadLibrary(path: ?[*:0]const u8) error{loadLibrary}!void {
        const result = raw_loadLibrary(path);
        if (!result) {
            log.err("{s}", .{getError()});
            return error.loadLibrary;
        }
    }
    const raw_getPresentationSupport = @extern(*const fn (instance: vk.Instance, pdevice: vk.PhysicalDevice, qfamilyindex: u32) callconv(.c) bool, .{ .name = "SDL_Vulkan_GetPresentationSupport" });
    pub fn getPresentationSupport(instance: vk.Instance, pdevice: vk.PhysicalDevice, qfamilyindex: u32) error{getPresentationSupport}!void {
        const result = raw_getPresentationSupport(instance, pdevice, qfamilyindex);
        if (!result) {
            log.err("{s}", .{getError()});
            return error.getPresentationSupport;
        }
    }

    const raw_getInstanceExtensions = @extern(*const fn (*u32) callconv(.c) ?[*]const [*:0]const u8, .{ .name = "SDL_Vulkan_GetInstanceExtensions" });
    pub fn getInstanceExtensions() error{getInstanceExtensions}![]const [*:0]const u8 {
        var count: u32 = undefined;
        var ptr = raw_getInstanceExtensions(&count) orelse {
            log.err("{s}", .{getError()});
            return error.getInstanceExtensions;
        };
        return ptr[0..count];
    }
    const raw_createSurface = @extern(*const fn (window: Window, instance: vk.Instance, allocator: ?*const vk.AllocationCallbacks, surface: *vk.SurfaceKHR) callconv(.c) bool, .{ .name = "SDL_Vulkan_CreateSurface" });
    pub fn createSurface(window: Window, instance: vk.Instance, allocator: ?*const vk.AllocationCallbacks) error{createSurface}!vk.SurfaceKHR {
        var surface: vk.SurfaceKHR = undefined;
        const result = raw_createSurface(window, instance, allocator, &surface);
        if (!result) {
            log.err("{s}", .{getError()});
            return error.createSurface;
        }
        return surface;
    }
    pub const getInstanceProcAddr = @extern(*const fn () callconv(.c) vk.pfn.vkGetInstanceProcAddr, .{ .name = "SDL_Vulkan_GetVkGetInstanceProcAddr" });
};
